# Generated by Django 4.2.13 on 2026-05-27 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('grid_emission_factor_kgco2e_per_kwh', models.DecimalField(decimal_places=6, default=0.233, help_text='kgCO2e per kWh consumed from the electricity grid', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ANALYST', 'Analyst'), ('ADMIN', 'Admin')], default='ANALYST', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL_PROCUREMENT', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('CORPORATE_TRAVEL', 'Corporate Travel')], max_length=40)),
                ('original_filename', models.CharField(max_length=512)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='1-indexed CSV row number')),
                ('raw_line', models.TextField(blank=True, help_text='The raw CSV line content')),
                ('error_type', models.CharField(choices=[('PARSE_ERROR', 'Parse Error'), ('MISSING_FIELD', 'Missing Required Field'), ('UNKNOWN_UNIT', 'Unknown Unit of Measure'), ('UNKNOWN_MATERIAL', 'Unknown Material / Emission Factor'), ('BAD_DATE', 'Unparseable Date'), ('UNKNOWN_ROUTE', 'Unknown IATA Route'), ('VALIDATION', 'Validation Error')], max_length=30)),
                ('error_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='core.uploadbatch')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('SAP_FUEL_PROCUREMENT', 'SAP Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('CORPORATE_TRAVEL', 'Corporate Travel')], max_length=40)),
                ('scope', models.IntegerField(choices=[(1, 'Scope 1 — Direct'), (2, 'Scope 2 — Indirect (Energy)'), (3, 'Scope 3 — Value Chain')])),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('activity_description', models.CharField(blank=True, max_length=512)),
                ('raw_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_value_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('kgco2e', models.DecimalField(decimal_places=4, max_digits=18)),
                ('emission_factor_used', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('NEEDS_DISTANCE', 'Needs Distance'), ('FLAGGED', 'Flagged'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked (Audit)')], default='PENDING', max_length=20)),
                ('flagged_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('analyst_notes', models.TextField(blank=True)),
                ('original_raw_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('original_raw_unit', models.CharField(blank=True, max_length=50)),
                ('original_kgco2e', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rows', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='core.uploadbatch')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rows', to='core.client')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_rows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date', 'site_name'],
                'indexes': [models.Index(fields=['client', 'status'], name='core_emissi_client__c3ac9e_idx'), models.Index(fields=['client', 'source_type'], name='core_emissi_client__9271d0_idx'), models.Index(fields=['client', 'scope'], name='core_emissi_client__d3ddb1_idx'), models.Index(fields=['batch'], name='core_emissi_batch_i_03e877_idx'), models.Index(fields=['activity_date'], name='core_emissi_activit_baca6c_idx')],
            },
        ),
    ]
